"""
Per-script file-existence guarantee.

For every input file each experiment's scripts read at runtime, this
suite asserts the file is reachable on disk under the wired
`shared_data/` layout. The test is partitioned into:

  * **raw inputs** — files that ship with the data drop (Recon3D SBML,
    TCGA expression matrices, HMA pseudolabels, GPR table, multi-seed
    predictions). These MUST exist for any user to run the pipeline.
    Failures here are blocking.

  * **intermediate artifacts** — files generated by an earlier stage of
    the pipeline (`hma_labels_thresholded.pt`, `splits.json`,
    `graph_structure.pt`, training-checkpoint `*.pt`, `test_scores.npz`).
    These are NOT raw inputs; they only exist after a user has run the
    upstream training scripts. We document them but don't fail when
    absent.

  * **download-on-demand** — files behind a data-use agreement
    (METABRIC, CPTAC-BRCA raw matrices, TCGA-LUAD raw STAR counts).
    These are documented in their respective `shared_data/<name>/README.md`
    but skipped by this test.

The strongest reproducibility statement this suite makes is:
**after `bash experiments/scripts/wire_shared_data.sh` runs cleanly,
every raw-input file that any script tries to open exists on disk.**
"""

from __future__ import annotations

from pathlib import Path

import pytest

from _paths import EXPERIMENTS_DIR, JOURNALS_DIR, SHARED_DATA_DIR


# ─────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────


def _exists(p: Path | str) -> bool:
    """True iff the path (or its symlink target) resolves to a real file/dir."""
    try:
        return Path(p).resolve(strict=False).exists()
    except OSError:
        return False


def _check(label: str, path: Path) -> None:
    """Helper for richer fail messages on `assert _exists`."""
    p = path.resolve(strict=False) if path.is_absolute() else path
    assert _exists(path), (
        f"Missing canonical input: {label}\n"
        f"  Expected at: {path}\n"
        f"  Resolves to: {p}\n"
        f"  Fix: run `bash experiments/scripts/wire_shared_data.sh` "
        f"or restore the source-of-truth tree."
    )


# ─────────────────────────────────────────────────────────────────────
# RAW INPUTS — these MUST exist after wire_shared_data.sh runs cleanly.
# Each entry is (label, relative-path-from-Journals-root).
# Grouped by the data category it covers.
# ─────────────────────────────────────────────────────────────────────


# Recon3D bipartite graph (every model-using script reads these)
RECON3D_INPUTS = [
    ("Recon3D SBML",
     "shared_data/recon3d/Recon3D.xml"),
    ("Recon3D stoichiometric matrix",
     "shared_data/recon3d/recon3d_stoich.h5"),
    ("Recon3D metabolite features X_M",
     "shared_data/recon3d/metabolite_features.h5"),
    ("Recon3D GPR rules table",
     "shared_data/recon3d/gpr_table.tsv"),
    ("Recon3D edge: substrate_of",
     "shared_data/recon3d/edge_indices/substrate_of.pt"),
    ("Recon3D edge: produces",
     "shared_data/recon3d/edge_indices/produces.pt"),
    ("Recon3D edge: shared_metabolite",
     "shared_data/recon3d/edge_indices/shared_metabolite.pt"),
]


# TCGA-CRC 220-cohort (E01 main inputs)
TCGA_CRC_220_INPUTS = [
    ("TCGA-CRC 220 clinical metadata (cohort-220 pipeline)",
     "shared_data/tcga_crc_220/cohort_220_clinical_metadata.tsv"),
    ("TCGA-CRC 220 metabolite features (cohort-220 pipeline)",
     "shared_data/tcga_crc_220/cohort_220_metabolite_features.h5"),
    ("TCGA-CRC 220 stoich matrix (cohort-220 pipeline)",
     "shared_data/tcga_crc_220/cohort_220_recon3d_stoich.h5"),
    ("TCGA-CRC 220 activity pseudolabels (cohort-220 pipeline)",
     "shared_data/tcga_crc_220/cohort_220_activity_pseudolabels.pt"),
    ("TCGA-CRC 220 edge_indices/substrate_of (cohort-220 pipeline)",
     "shared_data/tcga_crc_220/cohort_220_edge_indices/substrate_of.pt"),
    ("TCGA-CRC 220 edge_indices/produces (cohort-220 pipeline)",
     "shared_data/tcga_crc_220/cohort_220_edge_indices/produces.pt"),
    ("TCGA-CRC 220 edge_indices/shared_metabolite (cohort-220 pipeline)",
     "shared_data/tcga_crc_220/cohort_220_edge_indices/shared_metabolite.pt"),
    ("CPTAC-CRC protein matrix (220 cohort)",
     "shared_data/tcga_crc_220/cptac_crc_protein.h5"),
]


# TCGA-CRC 624-cohort (E03/E04/E05/E07 inputs)
TCGA_CRC_624_INPUTS = [
    ("TCGA-CRC 624 clinical metadata",
     "shared_data/tcga_crc_624/clinical_metadata.tsv"),
    ("TCGA-CRC 624 MSI labels (E07 input)",
     "shared_data/tcga_crc_624/clinical_metadata_msi.tsv"),
    ("TCGA-CRC 624 RNA-seq matrix (HDF5)",
     "shared_data/tcga_crc_624/tcga_crc_rnaseq.h5"),
    ("TCGA-CRC 624 RNA-seq matrix (CSV)",
     "shared_data/tcga_crc_624/tcga_rna_seq.csv"),
    ("Proteomics-available mask (CRC)",
     "shared_data/tcga_crc_624/proteomics_available_mask.pt"),
    ("TCGA-CRC 624 activity pseudolabels",
     "shared_data/tcga_crc_624/activity_pseudolabels.pt"),
    ("TCGA-CRC 624 metabolite features",
     "shared_data/tcga_crc_624/metabolite_features.h5"),
    ("TCGA-CRC 624 stoich matrix",
     "shared_data/tcga_crc_624/recon3d_stoich.h5"),
    ("TCGA-CRC 624 GPR table",
     "shared_data/tcga_crc_624/gpr_table.tsv"),
    ("TCGA-CRC 624 edge_indices/substrate_of",
     "shared_data/tcga_crc_624/edge_indices/substrate_of.pt"),
    ("TCGA-CRC 624 edge_indices/produces",
     "shared_data/tcga_crc_624/edge_indices/produces.pt"),
    ("TCGA-CRC 624 edge_indices/shared_metabolite",
     "shared_data/tcga_crc_624/edge_indices/shared_metabolite.pt"),
]


# HMA pseudolabels (every supervised script)
HMA_INPUTS = [
    ("HMA activity pseudolabels (Stage-2 fine-tuning target)",
     "shared_data/hma_labels/activity_pseudolabels.pt"),
    ("MSI coverage report (audit trail)",
     "shared_data/hma_labels/msi_coverage_report.txt"),
]


# GPR mask (E14 expansion sanity-check)
GPR_INPUTS = [
    ("GPR reaction mask (in-repo payload)",
     "shared_data/gpr_mask/gpr_reaction_mask.json"),
]


# Multi-seed predictions (E04 source_checkpoint, E07 RESULTS, E08, E09)
MULTISEED_624_INPUTS = [
    ("624-cohort Config B: seed_1/fold_0.csv",
     "shared_data/training_logs/results_multiseed_624_configB/seed_1/fold_0.csv"),
    ("624-cohort Config B: seed_1/fold_summary.json",
     "shared_data/training_logs/results_multiseed_624_configB/seed_1/fold_summary.json"),
    ("624-cohort Config B: seed_1/model_fold_0.pt",
     "shared_data/training_logs/results_multiseed_624_configB/seed_1/model_fold_0.pt"),
    ("624-cohort Config A: seed_1 dir",
     "shared_data/training_logs/results_multiseed_624_configA/seed_1"),
]


# 220-cohort multi-seed (E02 inputs)
MULTISEED_220_INPUTS = [
    ("220-cohort A baseline: seed_1 dir",
     "shared_data/training_logs/results_multiseed_220_A_baseline/seed_1"),
    ("220-cohort B1 apples-x-apples: seed_1 dir",
     "shared_data/training_logs/results_multiseed_220_B1_applesXapples/seed_1"),
]


# E14 fold-prediction inputs
E14_INPUTS = [
    ("E14: 624-cohort all_folds predictions",
     "shared_data/training_logs/fold_predictions/all_folds.csv"),
    ("E14: apple-to-apple 220-matched-624 predictions",
     "shared_data/training_logs/results_apple_to_apple/C1_220_matched_624/all_folds.csv"),
]


# TCGA-BRCA cross-cancer (E10)
TCGA_BRCA_INPUTS = [
    ("TCGA-BRCA TPM matrix (E10 02 input)",
     "shared_data/tcga_brca/tcga_brca_tpm_log2.tsv"),
    ("TCGA-BRCA gene symbol mapping (E10 02 input)",
     "shared_data/tcga_brca/gene_id_to_name.tsv"),
    ("TCGA-BRCA processed metabolite features",
     "shared_data/tcga_brca/processed/metabolite_features.h5"),
    ("TCGA-BRCA processed GPR table",
     "shared_data/tcga_brca/processed/gpr_table.tsv"),
    ("TCGA-BRCA processed patient list",
     "shared_data/tcga_brca/processed/patient_list.txt"),
    ("TCGA-BRCA processed activity_pseudolabels.pt",
     "shared_data/tcga_brca/processed/activity_pseudolabels.pt"),
    ("TCGA-BRCA processed activity_pseudolabels.npy",
     "shared_data/tcga_brca/processed/activity_pseudolabels.npy"),
    ("TCGA-BRCA edge_indices/substrate_of",
     "shared_data/tcga_brca/processed/edge_indices/substrate_of.pt"),
    ("TCGA-BRCA edge_indices/produces",
     "shared_data/tcga_brca/processed/edge_indices/produces.pt"),
    ("TCGA-BRCA edge_indices/shared_metabolite",
     "shared_data/tcga_brca/processed/edge_indices/shared_metabolite.pt"),
    ("TCGA-BRCA full-cohort 624 best_model.pt (cross-consortium ckpt)",
     "shared_data/tcga_brca/results_brca/full_cohort_624/best_model.pt"),
    ("TCGA-BRCA full-cohort 220 best_model.pt",
     "shared_data/tcga_brca/results_brca/full_cohort/best_model.pt"),
]


# TCGA-LUAD cross-cancer (E11) — partial; raw FASTQs are download-on-demand
TCGA_LUAD_INPUTS = [
    ("TCGA-LUAD full-cohort best_model.pt (E11 prediction ckpt)",
     "shared_data/tcga_luad/results_luad/full_cohort/best_model.pt"),
    ("TCGA-LUAD full-cohort test_scores.npz (E11 published-comparison input)",
     "shared_data/tcga_luad/results_luad/full_cohort/test_scores.npz"),
]


# DepMap raw GEMs (HMA pseudolabel generation)
DEPMAP_INPUTS = [
    ("DepMap HMA tissue GEMs directory",
     "shared_data/depmap/hma_tissue_gems"),
]


# Cross-experiment training-log payloads
TRAINING_LOG_INPUTS = [
    ("Stage-1 pretraining log",
     "shared_data/training_logs/stage1_pretrain_log.csv"),
    ("Stage-2 fine-tuning log (canonical figure source)",
     "shared_data/training_logs/stage2_finetune_log.csv"),
]


# ─────────────────────────────────────────────────────────────────────
# Aggregate every raw-input list into one parameterized test.
# ─────────────────────────────────────────────────────────────────────


_ALL_RAW_INPUTS = (
    [("Recon3D", *e) for e in RECON3D_INPUTS] +
    [("TCGA-CRC-220", *e) for e in TCGA_CRC_220_INPUTS] +
    [("TCGA-CRC-624", *e) for e in TCGA_CRC_624_INPUTS] +
    [("HMA labels", *e) for e in HMA_INPUTS] +
    [("GPR mask", *e) for e in GPR_INPUTS] +
    [("Multiseed-624", *e) for e in MULTISEED_624_INPUTS] +
    [("Multiseed-220", *e) for e in MULTISEED_220_INPUTS] +
    [("E14 inputs", *e) for e in E14_INPUTS] +
    [("TCGA-BRCA", *e) for e in TCGA_BRCA_INPUTS] +
    [("TCGA-LUAD", *e) for e in TCGA_LUAD_INPUTS] +
    [("DepMap", *e) for e in DEPMAP_INPUTS] +
    [("Training logs", *e) for e in TRAINING_LOG_INPUTS]
)


@pytest.mark.smoke
@pytest.mark.parametrize(
    "category,label,rel_path",
    _ALL_RAW_INPUTS,
    ids=[f"{cat}::{lbl}" for cat, lbl, _ in _ALL_RAW_INPUTS],
)
def test_raw_input_exists(category: str, label: str, rel_path: str):
    """For every raw input file referenced by any experiment script,
    the canonical shared_data/ path must resolve to an existing file
    or directory.

    Failures: run `bash experiments/scripts/wire_shared_data.sh`."""
    p = JOURNALS_DIR / rel_path
    _check(f"[{category}] {label}", p)


# ─────────────────────────────────────────────────────────────────────
# Directory-population checks (count of children matters)
# ─────────────────────────────────────────────────────────────────────


@pytest.mark.smoke
@pytest.mark.parametrize("label,root,min_count,glob", [
    (
        "TCGA-CRC 220-cohort per-patient h5 (cohort-220 pipeline)",
        "shared_data/tcga_crc_220/cohort_220_reaction_features",
        200,  # 220 patients
        "TCGA-*.h5",
    ),
    (
        "TCGA-CRC 624-cohort per-patient h5",
        "shared_data/tcga_crc_624/reaction_features",
        100,
        "TCGA-*.h5",
    ),
    (
        "TCGA-BRCA per-patient reaction features",
        "shared_data/tcga_brca/processed/reaction_features",
        100,
        "TCGA-*.h5",
    ),
    (
        "TCGA-BRCA raw STAR counts",
        "shared_data/tcga_brca/raw",
        100,
        "TCGA-*.star_gene_counts.tsv",
    ),
    (
        "DepMap HMA tissue GEMs (.mat files)",
        "shared_data/depmap/hma_tissue_gems",
        10,
        "*.mat",
    ),
])
def test_directory_populated(label: str, root: str, min_count: int, glob: str):
    """Critical input directories must have at least the documented
    number of children."""
    d = JOURNALS_DIR / root
    if not _exists(d):
        pytest.fail(f"{label}: directory missing — {d}")
    matches = list(Path(d.resolve(strict=False)).glob(glob))
    assert len(matches) >= min_count, (
        f"{label}: expected ≥{min_count} files matching '{glob}' under "
        f"{root}, got {len(matches)}."
    )


# ─────────────────────────────────────────────────────────────────────
# Multi-seed completeness — all 10 seeds × 5 folds for ConfigB
# ─────────────────────────────────────────────────────────────────────


@pytest.mark.smoke
def test_multiseed_624_configB_complete():
    """Every seed_*/ under ConfigB must have all 5 fold artefacts +
    fold_summary.json. This is what E07 / E04 / E08 / E09 expect."""
    d = JOURNALS_DIR / "shared_data/training_logs/results_multiseed_624_configB"
    assert _exists(d), f"{d} missing"
    seeds = sorted(p for p in Path(d.resolve(strict=False)).iterdir()
                   if p.is_dir() and p.name.startswith("seed_"))
    assert len(seeds) >= 10, f"expected ≥10 seeds, got {len(seeds)}"
    for seed_dir in seeds:
        for fold in range(5):
            for name in (f"fold_{fold}.csv", f"model_fold_{fold}.pt"):
                p = seed_dir / name
                assert p.exists(), f"Missing {seed_dir.name}/{name}"
        assert (seed_dir / "fold_summary.json").exists(), (
            f"Missing {seed_dir.name}/fold_summary.json"
        )
        # all_folds.csv is the merged per-seed per-fold table
        assert (seed_dir / "all_folds.csv").exists(), (
            f"Missing {seed_dir.name}/all_folds.csv"
        )


# ─────────────────────────────────────────────────────────────────────
# Per-script "everything I need to read exists" sanity tests for the
# scripts that have safe defaults.
# ─────────────────────────────────────────────────────────────────────


def _import_safe(rel_path: str):
    """Import a script without running its main(), returning the module
    or None if heavy deps are missing."""
    import importlib.util
    p = EXPERIMENTS_DIR / rel_path
    if not p.exists():
        return None
    try:
        spec = importlib.util.spec_from_file_location(p.stem, str(p))
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod
    except (ImportError, ModuleNotFoundError):
        return None


@pytest.mark.smoke
def test_E07_script_inputs_resolve():
    """E07 reads CLIN + every fold_*.csv under RESULTS/seed_*/."""
    mod = _import_safe("E07_msi_stratified/code/msi_stratified_624_configB.py")
    assert mod is not None, "E07 script could not be imported"
    _check("E07 CLIN", Path(mod.CLIN))
    _check("E07 RESULTS", Path(mod.RESULTS))
    seed_dirs = sorted(p for p in mod.RESULTS.iterdir()
                       if p.is_dir() and p.name.startswith("seed_"))
    assert len(seed_dirs) >= 10
    # Every fold_*.csv that the script will iterate over must exist.
    for seed_dir in seed_dirs:
        for fold_csv in sorted(seed_dir.glob("fold_*.csv")):
            assert fold_csv.exists(), f"Missing {fold_csv}"


@pytest.mark.smoke
def test_E14_run_fba_624_inputs_resolve():
    mod = _import_safe("E14_fba_viability/code/run_fba_624.py")
    assert mod is not None, "E14 run_fba_624 could not be imported"
    p = mod._default_paths()
    _check("E14 run_fba_624 --predictions", p["predictions"])
    _check("E14 run_fba_624 --recon3d", p["recon3d"])


@pytest.mark.smoke
def test_E14_run_fba_apple_to_apple_inputs_resolve():
    mod = _import_safe("E14_fba_viability/code/run_fba_apple_to_apple.py")
    assert mod is not None, "E14 run_fba_apple_to_apple could not be imported"
    p = mod._default_paths()
    _check("E14 a2a --recon3d", p["recon3d"])
    _check("E14 a2a --pred_220", p["pred_220"])
    _check("E14 a2a --pred_624", p["pred_624"])


# ─────────────────────────────────────────────────────────────────────
# Documented intermediate-artifact / download-on-demand status.
# These are NOT failures — just visibility into what the user must
# generate or fetch.
# ─────────────────────────────────────────────────────────────────────


_INTERMEDIATE_ARTIFACTS = [
    # (description, list of paths that would exist after running the
    #  upstream pipeline). These are NOT raw inputs — they are
    #  downstream outputs of E01 / E10 / E11 training, included here
    #  so the developer can see what's missing if a downstream script
    #  refers to them.
    (
        "Stage-1/2 training intermediates (only present after running "
        "03_train_metagnn.py + 04_evaluate_metagnn.py inside the user's "
        "own --data_root). The cohort_220_source/data/ tree exposes "
        "the canonical 220 versions; the 624 versions are only emitted "
        "when the H100 multi-seed pipeline runs.",
        [
            # We probe each under cohort_220_source as the canonical
            # 220-cohort drop, since that's what ships in this repo.
            "cohort_220_source/data/activity_pseudolabels.pt",
            "cohort_220_source/data/metabolite_features.h5",
            "cohort_220_source/data/recon3d_stoich.h5",
        ],
    ),
    (
        "compute_baselines.py / validate_fba.py expect a user --base_dir "
        "with `data/processed/{splits.json, hma_labels_thresholded.pt, "
        "graph_structure.pt, reaction_ids.json}` plus "
        "`results/results_summary_v2.json`. These ship only in the "
        "user's own pipeline output, not in shared_data/.",
        [
            "cohort_220_source/data/processed/hma_labels_thresholded.pt",
            "cohort_220_source/data/processed/splits.json",
        ],
    ),
]


def test_intermediate_artifacts_documented():
    """Documentation-only test: lists pipeline-output files that
    *aren't* raw inputs. Always passes; serves as developer guidance."""
    msg = ["The following are PIPELINE OUTPUTS, not raw inputs:"]
    for desc, paths in _INTERMEDIATE_ARTIFACTS:
        msg.append(f"\n{desc}")
        for p in paths:
            full = JOURNALS_DIR / p
            present = "✓" if _exists(full) else "—"
            msg.append(f"  {present} {p}")
    # Always passes; just print the inventory.
    print("\n".join(msg))


# ─────────────────────────────────────────────────────────────────────
# Regression: no script ships hardcoded personal paths
# ─────────────────────────────────────────────────────────────────────


@pytest.mark.smoke
def test_no_hardcoded_personal_paths_in_runnable_scripts():
    """Catch regressions: no runnable script under experiments/ should
    ship a /Users/... or /home/<user>/... path in code (not counting
    comments/docstrings)."""
    bad_patterns = (
        "/Users/<user>",
        "/sessions/<session>",
        "/home/<user>",
    )
    offenders = []
    scripts = list(EXPERIMENTS_DIR.rglob("*.py")) + list(EXPERIMENTS_DIR.rglob("*.sh"))
    for py in scripts:
        if "__pycache__" in py.parts or "/tests/" in str(py):
            continue
        text = py.read_text(encoding="utf-8", errors="replace")
        for lineno, line in enumerate(text.splitlines(), 1):
            stripped = line.lstrip()
            if stripped.startswith(("#", '"', "'")):
                continue
            for pat in bad_patterns:
                if pat in line:
                    offenders.append(f"{py}:{lineno}: {line.strip()}")
    if offenders:
        msg = "\n".join(offenders[:20])
        pytest.fail(
            f"{len(offenders)} hardcoded personal path(s) in runnable scripts:\n{msg}"
        )
