#!/usr/bin/env python3
"""
MetaGNN-CRC: Automated Raw Data Download Script
=================================================
Downloads all raw data required for the 690-patient dataset generation.

PREREQUISITES:
  pip install requests cptac gdc-vos tqdm --break-system-packages
  # For gdc-client: download binary from https://gdc.cancer.gov/access-data/gdc-data-transfer-tool
  # OR: conda install -c bioconda gdc-client

USAGE:
  python download_all_raw_data.py --output_dir ./raw_downloads

  # Then run the processing pipeline:
  python 00_download_and_generate_690.py \
      --gdc_dir ./raw_downloads/gdc_star_counts \
      --gdc_manifest ./raw_downloads/gdc_manifest.tsv \
      --cptac_tsv ./raw_downloads/cptac_colon_proteomics.tsv \
      --cptac_clinical ./raw_downloads/cptac_colon_clinical.tsv \
      --recon3d_mat ./raw_downloads/Recon3DModel_301.mat \
      --hma_mat ./raw_downloads/Human-GEM.mat \
      --output_dir ./processed_690

WHAT THIS SCRIPT DOWNLOADS:
  1. TCGA-COAD/READ RNA-seq STAR counts from GDC     (~40 GB)
     https://portal.gdc.cancer.gov
  2. CPTAC colon proteomics via cptac Python package  (~200 MB)
     https://pdc.cancer.gov (via: pip install cptac)
  3. Recon3D v3.0 MATLAB model from VMH               (~320 MB)
     https://www.vmh.life/#downloadview
  4. HMA tissue-specific GEMs from Zenodo #3583004    (~500 MB)
     https://zenodo.org/record/3583004
     (Robinson et al. 2020 "An Atlas of Human Metabolism")
  5. Recon3D.xml from BiGG for FBA experiments        (~100 MB)
     http://bigg.ucsd.edu/static/models/Recon3D.xml.gz

TOTAL: ~41 GB download, allow 1-3 hours depending on connection speed.
NOTE: PubChem metabolite properties (~5 MB) are auto-generated by
      00_download_and_generate_690.py if not provided.

Author: Thiptanawat Phongwattana
Affiliation: School of Information Technology, KMUTT
"""

import os
import sys
import json
import shutil
import subprocess
import logging
import argparse
import time
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler('download_raw_data.log'),
    ]
)
logger = logging.getLogger(__name__)


def check_dependencies():
    """Check that required tools and packages are available."""
    issues = []

    # Check Python packages
    for pkg in ['requests', 'pandas', 'numpy', 'tqdm']:
        try:
            __import__(pkg)
        except ImportError:
            issues.append(f"Missing Python package: {pkg}  → pip install {pkg}")

    # Check gdc-client (optional but needed for Step 1)
    gdc_path = shutil.which('gdc-client')
    if gdc_path is None:
        issues.append(
            "gdc-client not found in PATH.\n"
            "  Install option 1: conda install -c bioconda gdc-client\n"
            "  Install option 2: Download from https://gdc.cancer.gov/access-data/gdc-data-transfer-tool\n"
            "  Install option 3: This script will try to use the GDC API as fallback"
        )
    else:
        logger.info(f"gdc-client found: {gdc_path}")

    if issues:
        logger.warning("Some dependencies missing (may affect certain steps):")
        for issue in issues:
            logger.warning(f"  • {issue}")
    else:
        logger.info("All dependencies satisfied")

    return len(issues) == 0


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 1: Download TCGA RNA-seq from GDC
# ═══════════════════════════════════════════════════════════════════════════════

def download_gdc_rnaseq(output_dir: str) -> str:
    """
    Download TCGA-COAD/READ RNA-seq STAR gene counts from GDC.

    Returns path to the manifest file.
    """
    import requests

    gdc_dir = os.path.join(output_dir, 'gdc_star_counts')
    manifest_path = os.path.join(output_dir, 'gdc_manifest.tsv')
    os.makedirs(gdc_dir, exist_ok=True)

    # ─── Step 1a: Query GDC API for file list ─────────────────────────────
    logger.info("=" * 60)
    logger.info("STEP 1: Downloading TCGA-COAD/READ RNA-seq from GDC")
    logger.info("=" * 60)

    filters = {
        "op": "and",
        "content": [
            {
                "op": "in",
                "content": {
                    "field": "cases.project.project_id",
                    "value": ["TCGA-COAD", "TCGA-READ"]
                }
            },
            {
                "op": "=",
                "content": {
                    "field": "data_category",
                    "value": "Transcriptome Profiling"
                }
            },
            {
                "op": "=",
                "content": {
                    "field": "data_type",
                    "value": "Gene Expression Quantification"
                }
            },
            {
                "op": "=",
                "content": {
                    "field": "analysis.workflow_type",
                    "value": "STAR - Counts"
                }
            },
        ]
    }

    params = {
        "filters": json.dumps(filters),
        "fields": (
            "file_id,file_name,file_size,md5sum,state,"
            "cases.submitter_id,cases.project.project_id,"
            "cases.samples.sample_type"
        ),
        "format": "JSON",
        "size": "2000",
    }

    logger.info("Querying GDC API for TCGA-COAD/READ STAR count files...")
    resp = requests.get("https://api.gdc.cancer.gov/files", params=params)
    resp.raise_for_status()
    data = resp.json()
    hits = data['data']['hits']
    logger.info(f"GDC API returned {len(hits)} files")

    # Filter to Primary Tumor samples only
    primary_hits = []
    for h in hits:
        samples = []
        for c in h.get('cases', []):
            for s in c.get('samples', []):
                samples.append(s.get('sample_type', ''))
        if any('Primary Tumor' in s or 'Primary' in s for s in samples):
            primary_hits.append(h)

    if not primary_hits:
        # If sample_type filtering doesn't work, keep all
        primary_hits = hits
        logger.warning("Could not filter by sample type — keeping all files")

    logger.info(f"After Primary Tumor filter: {len(primary_hits)} files")

    # ─── Step 1b: Write GDC manifest ──────────────────────────────────────
    manifest_rows = []
    case_mapping_rows = []
    for h in primary_hits:
        case_id = ''
        project = ''
        for c in h.get('cases', []):
            case_id = c.get('submitter_id', '')
            project = c.get('project', {}).get('project_id', '')
            break

        manifest_rows.append({
            'id': h['file_id'],
            'filename': h['file_name'],
            'md5': h.get('md5sum', ''),
            'size': h.get('file_size', 0),
            'state': h.get('state', 'released'),
        })
        case_mapping_rows.append({
            'id': h['file_id'],
            'filename': h['file_name'],
            'case_id': case_id,
            'project': project,
            'size': h.get('file_size', 0),
        })

    import pandas as pd

    # Save standard GDC manifest (for gdc-client)
    manifest_df = pd.DataFrame(manifest_rows)
    manifest_df.to_csv(manifest_path, sep='\t', index=False)
    logger.info(f"GDC manifest saved: {manifest_path} ({len(manifest_df)} files)")

    # Save case mapping (for our processing pipeline)
    case_df = pd.DataFrame(case_mapping_rows)
    case_path = manifest_path.replace('.tsv', '_with_cases.tsv')
    case_df.to_csv(case_path, sep='\t', index=False)
    logger.info(f"Case mapping saved: {case_path}")

    # ─── Step 1c: Download using gdc-client ───────────────────────────────
    gdc_client = shutil.which('gdc-client')

    if gdc_client:
        logger.info(f"\nDownloading {len(manifest_df)} files with gdc-client...")
        logger.info(f"Output directory: {gdc_dir}")
        logger.info("This may take 30-120 minutes depending on connection speed...\n")

        cmd = [
            gdc_client, 'download',
            '-m', manifest_path,
            '-d', gdc_dir,
            '--n-processes', '4',     # parallel downloads
            '--retry-amount', '5',
        ]
        result = subprocess.run(cmd, capture_output=False)
        if result.returncode != 0:
            logger.error("gdc-client download failed — see output above")
            logger.info("You can retry manually: gdc-client download -m "
                        f"{manifest_path} -d {gdc_dir}")
        else:
            logger.info("GDC download complete!")
    else:
        # Fallback: download via GDC API (slower, one at a time)
        logger.info("\ngdc-client not available — using GDC API direct download")
        logger.info("(This is slower; consider installing gdc-client for parallel downloads)")

        from tqdm import tqdm

        for i, row in tqdm(enumerate(manifest_rows), total=len(manifest_rows),
                           desc="Downloading GDC files"):
            file_id = row['id']
            filename = row['filename']
            out_dir = os.path.join(gdc_dir, file_id)
            out_path = os.path.join(out_dir, filename)

            if os.path.exists(out_path):
                continue  # already downloaded

            os.makedirs(out_dir, exist_ok=True)

            url = f"https://api.gdc.cancer.gov/data/{file_id}"
            try:
                r = requests.get(url, stream=True, timeout=60)
                r.raise_for_status()
                with open(out_path, 'wb') as f:
                    for chunk in r.iter_content(chunk_size=8192):
                        f.write(chunk)
            except Exception as e:
                logger.warning(f"Failed to download {file_id}: {e}")
                continue

        logger.info("GDC API download complete!")

    # Count downloaded files
    n_downloaded = sum(1 for d in os.listdir(gdc_dir)
                       if os.path.isdir(os.path.join(gdc_dir, d)))
    logger.info(f"Downloaded files: {n_downloaded} / {len(manifest_df)}")

    return manifest_path


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 2: Download CPTAC proteomics
# ═══════════════════════════════════════════════════════════════════════════════

def download_cptac_proteomics(output_dir: str) -> tuple:
    """
    Download CPTAC colon cancer proteomics using the cptac Python package.
    Falls back to direct PDC API download if the package has internal bugs.

    Returns (proteomics_tsv_path, clinical_tsv_path).
    """
    logger.info("\n" + "=" * 60)
    logger.info("STEP 2: Downloading CPTAC colon cancer proteomics")
    logger.info("=" * 60)

    prot_tsv = os.path.join(output_dir, 'cptac_colon_proteomics.tsv')
    clin_tsv = os.path.join(output_dir, 'cptac_colon_clinical.tsv')

    if os.path.exists(prot_tsv) and os.path.exists(clin_tsv):
        logger.info("CPTAC data already exists — skipping download")
        return prot_tsv, clin_tsv

    # ─── Method 1: cptac Python package ────────────────────────────────────
    try:
        import cptac
        import pandas as pd

        logger.info("Loading CPTAC Colon dataset (auto-downloads on first use)...")
        cptac_ver = getattr(cptac, '__version__', getattr(cptac, 'version', 'unknown'))
        if callable(cptac_ver):
            cptac_ver = 'unknown (version is a callable)'
        logger.info(f"cptac version: {cptac_ver}")

        # Discover available dataset names
        colon = None
        for attr_name in ['Coad', 'Colon', 'coad', 'colon']:
            cls = getattr(cptac, attr_name, None)
            if cls is not None and callable(cls):
                logger.info(f"Found dataset class: cptac.{attr_name}")
                colon = cls()
                break

        if colon is None:
            available = [a for a in dir(cptac)
                         if not a.startswith('_') and callable(getattr(cptac, a, None))]
            raise AttributeError(
                f"No colon cancer class found. Available: {available}")

        # Try multiple approaches to extract proteomics
        prot_df = None

        # Approach A: specify source explicitly (avoids the generator/len bug)
        for source in ['umich', 'bcm', 'washu', 'broad']:
            try:
                logger.info(f"  Trying get_proteomics(source='{source}')...")
                prot_df = colon.get_proteomics(source=source)
                logger.info(f"  Success with source='{source}': shape {prot_df.shape}")
                break
            except TypeError as te:
                if 'generator' in str(te) or 'len' in str(te):
                    logger.warning(f"  source='{source}' hit generator/len bug: {te}")
                    continue
                else:
                    raise
            except Exception as e:
                logger.warning(f"  source='{source}' failed: {e}")
                continue

        # Approach B: monkey-patch the bug and retry without source
        if prot_df is None:
            logger.info("  All sources failed — trying monkey-patch workaround...")
            try:
                import cptac.cancers.cancer as cancer_mod
                _original_get_df = cancer_mod.Cancer.get_dataframe

                def _patched_get_dataframe(self, *args, **kwargs):
                    """Patch: convert generator to list before len() call."""
                    try:
                        return _original_get_df(self, *args, **kwargs)
                    except TypeError as e:
                        if 'generator' in str(e) and 'len' in str(e):
                            # Retry with the internal method patched
                            raise
                        raise

                # Direct attribute access to the internal data
                if hasattr(colon, '_data'):
                    for key in colon._data:
                        if 'proteomics' in key.lower():
                            data_dict = colon._data[key]
                            if isinstance(data_dict, dict):
                                # Take the first available source
                                for src_name, df in data_dict.items():
                                    if hasattr(df, 'shape'):
                                        prot_df = df
                                        logger.info(
                                            f"  Extracted proteomics directly from "
                                            f"_data['{key}']['{src_name}']: {df.shape}")
                                        break
                            elif hasattr(data_dict, 'shape'):
                                prot_df = data_dict
                                logger.info(
                                    f"  Extracted proteomics directly from "
                                    f"_data['{key}']: {data_dict.shape}")
                            if prot_df is not None:
                                break
            except Exception as e:
                logger.warning(f"  Monkey-patch approach failed: {e}")

        if prot_df is None:
            raise RuntimeError(
                "cptac package bug: get_proteomics() crashes with "
                "'TypeError: object of type generator has no len()'. "
                "Falling back to PDC API download.")

        # Successfully got proteomics — save it
        logger.info(f"Proteomics shape: {prot_df.shape}")

        if isinstance(prot_df.columns, pd.MultiIndex):
            prot_df.columns = ['_'.join(str(c) for c in col).strip('_')
                               for col in prot_df.columns.values]

        prot_out = prot_df.T
        prot_out.index.name = 'Gene'
        prot_out.to_csv(prot_tsv, sep='\t')
        logger.info(f"Proteomics saved: {prot_out.shape} → {prot_tsv}")

        # Get clinical data
        logger.info("Extracting clinical DataFrame...")
        clin_df = colon.get_clinical()
        clin_df.index.name = 'Patient_ID'
        clin_df['tcga_barcode'] = clin_df.index
        clin_df['aliquot_id'] = clin_df.index
        clin_df.to_csv(clin_tsv, sep='\t')
        logger.info(f"Clinical saved: {clin_df.shape} → {clin_tsv}")

        return prot_tsv, clin_tsv

    except ImportError:
        logger.warning(
            "cptac package not installed. Trying PDC API fallback...")

    except Exception as e:
        logger.warning(f"cptac package failed: {e}")
        logger.info("Trying PDC API fallback...")

    # ─── Method 2: Download directly from PDC API ──────────────────────────
    try:
        import requests
        import pandas as pd

        logger.info("\nDownloading CPTAC proteomics directly from PDC API...")

        # PDC GraphQL endpoint
        pdc_url = "https://pdc.cancer.gov/graphql"

        # Step 2a: Find the CPTAC Colon Cancer study
        study_query = """
        {
            studySearch(name: "CPTAC COAD" acceptDUA: true) {
                studies {
                    study_id
                    study_name
                    disease_type
                    analytical_fraction
                    experiment_type
                }
            }
        }
        """
        logger.info("Querying PDC for CPTAC colon studies...")
        resp = requests.post(pdc_url, json={"query": study_query}, timeout=60)
        resp.raise_for_status()
        studies = resp.json().get('data', {}).get('studySearch', {}).get('studies', [])

        # Filter for proteomics (not phosphoproteomics)
        prot_studies = [s for s in studies
                        if 'proteome' in s.get('analytical_fraction', '').lower()
                        or 'proteom' in s.get('experiment_type', '').lower()]

        if not prot_studies:
            # Broader search
            study_query2 = """
            {
                studySearch(name: "Colon" acceptDUA: true) {
                    studies {
                        study_id
                        study_name
                        disease_type
                        analytical_fraction
                        experiment_type
                    }
                }
            }
            """
            resp2 = requests.post(pdc_url, json={"query": study_query2}, timeout=60)
            resp2.raise_for_status()
            studies2 = resp2.json().get('data', {}).get('studySearch', {}).get('studies', [])
            prot_studies = [s for s in studies2
                           if 'proteome' in s.get('analytical_fraction', '').lower()]

        if not prot_studies:
            logger.error("Could not find CPTAC colon proteomics study on PDC")
            logger.info(f"Studies found: {[s.get('study_name') for s in studies]}")
            raise RuntimeError("No CPTAC colon proteomics study found")

        study = prot_studies[0]
        study_id = study['study_id']
        logger.info(f"Found study: {study['study_name']} (ID: {study_id})")
        logger.info(f"  Disease: {study.get('disease_type')}")
        logger.info(f"  Fraction: {study.get('analytical_fraction')}")

        # Step 2b: Get quantitative data
        quant_query = """
        {{
            quantDataMatrix(
                study_id: "{study_id}"
                data_type: "log2_ratio"
                acceptDUA: true
            )
        }}
        """.format(study_id=study_id)

        logger.info("Downloading quantitative proteomics matrix (this may take a minute)...")
        resp = requests.post(pdc_url, json={"query": quant_query}, timeout=300)
        resp.raise_for_status()

        matrix_data = resp.json().get('data', {}).get('quantDataMatrix', [])

        if matrix_data and len(matrix_data) > 1:
            # First row is header (aliquot IDs), rest are gene rows
            header = matrix_data[0]
            rows = matrix_data[1:]

            # Build DataFrame
            import numpy as np
            gene_names = [row[0] for row in rows]
            values = []
            for row in rows:
                vals = []
                for v in row[1:]:
                    try:
                        vals.append(float(v) if v not in (None, '', 'NA') else np.nan)
                    except (ValueError, TypeError):
                        vals.append(np.nan)
                values.append(vals)

            prot_df = pd.DataFrame(
                values,
                index=gene_names,
                columns=header[1:]  # aliquot IDs
            )
            prot_df.index.name = 'Gene'
            prot_df.to_csv(prot_tsv, sep='\t')
            logger.info(f"PDC proteomics saved: {prot_df.shape} → {prot_tsv}")

            # Create minimal clinical TSV with patient IDs
            patient_ids = list(prot_df.columns)
            clin_df = pd.DataFrame({'Patient_ID': patient_ids})
            clin_df['tcga_barcode'] = clin_df['Patient_ID']
            clin_df['aliquot_id'] = clin_df['Patient_ID']
            clin_df.set_index('Patient_ID', inplace=True)
            clin_df.to_csv(clin_tsv, sep='\t')
            logger.info(f"Clinical IDs saved: {clin_df.shape} → {clin_tsv}")

            return prot_tsv, clin_tsv

        else:
            logger.error("PDC returned empty quantitative matrix")
            raise RuntimeError("Empty PDC response")

    except Exception as e:
        logger.error(f"PDC API download also failed: {e}")
        import traceback
        traceback.print_exc()
        logger.info(
            "\n╔══════════════════════════════════════════════════════════╗\n"
            "║  CPTAC proteomics could not be downloaded.              ║\n"
            "║  This is OK for initial runs — only 95/690 patients     ║\n"
            "║  have CPTAC data; the rest are zero-filled anyway.      ║\n"
            "║                                                         ║\n"
            "║  To download manually:                                  ║\n"
            "║  1. Go to: https://pdc.cancer.gov                       ║\n"
            "║  2. Search for 'CPTAC Colon' → Proteome study           ║\n"
            "║  3. Download the quantitative data matrix                ║\n"
            f"║  4. Save as: {prot_tsv:<40}║\n"
            "╚══════════════════════════════════════════════════════════╝"
        )
        return None, None


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 3: Download Recon3D MATLAB model
# ═══════════════════════════════════════════════════════════════════════════════

def download_recon3d(output_dir: str) -> str:
    """
    Download Recon3D v3.01 MATLAB model from VMH.

    The .mat file is hosted at:
      https://www.vmh.life/files/reconstructions/Recon/3.01/Recon3DModel_301.mat

    Returns path to .mat file.
    """
    import requests
    from tqdm import tqdm

    logger.info("\n" + "=" * 60)
    logger.info("STEP 3: Downloading Recon3D v3.01 MATLAB model")
    logger.info("=" * 60)

    mat_path = os.path.join(output_dir, 'Recon3DModel_301.mat')

    if os.path.exists(mat_path):
        size_mb = os.path.getsize(mat_path) / (1024**2)
        if size_mb > 1.0:  # Actual file is ~1.4 MB (compressed sparse matrices)
            logger.info(f"Recon3D already exists ({size_mb:.1f} MB) — skipping")
            return mat_path

    # Try known VMH download URLs (in order of preference)
    urls = [
        "https://www.vmh.life/files/reconstructions/Recon/3.01/Recon3DModel_301.mat",
        "https://www.vmh.life/files/reconstructions/Recon/3.0/Recon3D.mat",
        "https://www.vmh.life/files/reconstructions/Recon/Recon3DModel_301.mat",
    ]

    for url in urls:
        logger.info(f"Trying: {url}")
        try:
            resp = requests.get(url, stream=True, timeout=30)
            if resp.status_code == 200:
                total = int(resp.headers.get('content-length', 0))
                with open(mat_path, 'wb') as f:
                    with tqdm(total=total, unit='B', unit_scale=True,
                              desc="Recon3D.mat") as pbar:
                        for chunk in resp.iter_content(chunk_size=65536):
                            f.write(chunk)
                            pbar.update(len(chunk))

                size_mb = os.path.getsize(mat_path) / (1024**2)
                logger.info(f"Recon3D downloaded: {size_mb:.0f} MB → {mat_path}")
                return mat_path
            else:
                logger.warning(f"  HTTP {resp.status_code} — trying next URL")
        except Exception as e:
            logger.warning(f"  Failed: {e} — trying next URL")

    # If auto-download fails, provide manual instructions
    logger.error(
        "\nCould not auto-download Recon3D .mat file.\n"
        "Please download manually:\n"
        "  1. Go to: https://www.vmh.life/#downloadview\n"
        "  2. Download 'Recon3DModel_301.mat' (MATLAB format)\n"
        f"  3. Save to: {mat_path}\n"
        "  4. Re-run this script"
    )
    return mat_path


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4: Download HMA tissue-specific GEMs (for activity pseudo-labels)
# ═══════════════════════════════════════════════════════════════════════════════

def download_hma_tissue_gems(output_dir: str) -> str:
    """
    Download the 98 tissue-specific GEMs from Robinson et al. 2020
    "An Atlas of Human Metabolism" (Science Signaling).

    Source: Zenodo record 3583004
      https://zenodo.org/record/3583004

    The tINIT_GEMs/ directory in this archive contains the pre-generated
    tissue-specific models used for activity pseudo-labels.

    Returns path to the extracted data directory.
    """
    import requests
    import zipfile
    from tqdm import tqdm

    logger.info("\n" + "=" * 60)
    logger.info("STEP 4: Downloading HMA tissue-specific GEMs")
    logger.info("         (Robinson et al. 2020, Zenodo #3583004)")
    logger.info("=" * 60)

    hma_dir = os.path.join(output_dir, 'hma_tissue_gems')
    zip_path = os.path.join(output_dir, 'zenodo_3583004.zip')

    # Check if already extracted
    if os.path.isdir(hma_dir):
        mat_files = [f for f in os.listdir(hma_dir) if f.endswith('.mat')]
        if mat_files:
            logger.info(f"HMA data already exists ({len(mat_files)} .mat files) — skipping")
            # Return the first .mat file found
            return os.path.join(hma_dir, mat_files[0])

    os.makedirs(hma_dir, exist_ok=True)

    # ─── Method 1: Zenodo API ─────────────────────────────────────────────
    logger.info("Querying Zenodo API for record 3583004...")
    try:
        api_url = "https://zenodo.org/api/records/3583004"
        resp = requests.get(api_url, timeout=30)
        resp.raise_for_status()
        record = resp.json()

        # Find the main archive file
        files = record.get('files', [])
        logger.info(f"Found {len(files)} files in Zenodo record:")

        target_file = None
        for f in files:
            fname = f.get('key', f.get('filename', ''))
            fsize = f.get('size', 0)
            logger.info(f"  {fname} ({fsize / (1024**2):.1f} MB)")

            # Look for the main zip/tar archive or tINIT_GEMs specifically
            if 'tinit' in fname.lower() or fname.endswith('.zip'):
                target_file = f
            elif target_file is None:
                target_file = f  # fallback: take the first/largest file

        if target_file:
            fname = target_file.get('key', target_file.get('filename', ''))
            # Zenodo download URL
            download_url = target_file.get('links', {}).get('self', '')
            if not download_url:
                download_url = f"https://zenodo.org/records/3583004/files/{fname}?download=1"

            logger.info(f"\nDownloading: {fname}")
            logger.info(f"URL: {download_url}")

            resp = requests.get(download_url, stream=True, timeout=30)
            resp.raise_for_status()
            total = int(resp.headers.get('content-length', 0))

            dl_path = os.path.join(output_dir, fname)
            with open(dl_path, 'wb') as f:
                with tqdm(total=total, unit='B', unit_scale=True,
                          desc=fname) as pbar:
                    for chunk in resp.iter_content(chunk_size=65536):
                        f.write(chunk)
                        pbar.update(len(chunk))

            # Extract if it's a zip
            if dl_path.endswith('.zip'):
                logger.info(f"Extracting {fname}...")
                with zipfile.ZipFile(dl_path, 'r') as z:
                    # Extract .mat files to hma_dir
                    for member in z.namelist():
                        if member.endswith('.mat'):
                            # Extract with flat name
                            basename = os.path.basename(member)
                            target = os.path.join(hma_dir, basename)
                            with z.open(member) as src, open(target, 'wb') as dst:
                                shutil.copyfileobj(src, dst)
                            logger.info(f"  Extracted: {basename}")
                    # Also extract any directory named tINIT_GEMs
                    for member in z.namelist():
                        if 'tINIT' in member or 'tinit' in member.lower():
                            z.extract(member, hma_dir)
                os.remove(dl_path)

            elif dl_path.endswith('.mat'):
                shutil.move(dl_path, os.path.join(hma_dir, fname))

            # Find the main .mat file
            mat_files = []
            for root, dirs, files_list in os.walk(hma_dir):
                for f in files_list:
                    if f.endswith('.mat'):
                        mat_files.append(os.path.join(root, f))

            if mat_files:
                logger.info(f"HMA tissue GEMs ready: {len(mat_files)} .mat files in {hma_dir}")
                return mat_files[0]  # Return first .mat file

    except Exception as e:
        logger.warning(f"Zenodo API download failed: {e}")

    # ─── Method 2: Direct Zenodo download URL ─────────────────────────────
    direct_urls = [
        "https://zenodo.org/records/3583004/files/Human-GEM-atlas-data.zip?download=1",
        "https://zenodo.org/record/3583004/files/Atlas_of_Human_Metabolism_supplementary.zip?download=1",
    ]

    for url in direct_urls:
        logger.info(f"Trying direct URL: {url}")
        try:
            resp = requests.get(url, stream=True, timeout=30, allow_redirects=True)
            if resp.status_code == 200:
                total = int(resp.headers.get('content-length', 0))
                with open(zip_path, 'wb') as f:
                    with tqdm(total=total, unit='B', unit_scale=True,
                              desc="HMA data") as pbar:
                        for chunk in resp.iter_content(chunk_size=65536):
                            f.write(chunk)
                            pbar.update(len(chunk))

                if os.path.getsize(zip_path) > 1000:
                    logger.info("Extracting...")
                    with zipfile.ZipFile(zip_path, 'r') as z:
                        z.extractall(hma_dir)
                    os.remove(zip_path)

                    mat_files = []
                    for root, dirs, files_list in os.walk(hma_dir):
                        for f in files_list:
                            if f.endswith('.mat'):
                                mat_files.append(os.path.join(root, f))
                    if mat_files:
                        logger.info(f"HMA ready: {len(mat_files)} .mat files")
                        return mat_files[0]
        except Exception as e:
            logger.warning(f"  Failed: {e}")

    # ─── Fallback: manual instructions ────────────────────────────────────
    logger.error(
        "\n╔══════════════════════════════════════════════════════════╗\n"
        "║  Could not auto-download HMA tissue GEMs.              ║\n"
        "║  Please download manually:                              ║\n"
        "║                                                         ║\n"
        "║  1. Go to: https://zenodo.org/record/3583004            ║\n"
        "║  2. Download the archive file (.zip)                    ║\n"
        "║  3. Extract the .mat file(s) from tINIT_GEMs/           ║\n"
        f"║  4. Place into: {hma_dir:<40}║\n"
        "║  5. Re-run this script                                  ║\n"
        "╚══════════════════════════════════════════════════════════╝"
    )
    return os.path.join(hma_dir, 'tINIT_GEMs.mat')


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 5: Download Recon3D XML for FBA (optional, separate from .mat)
# ═══════════════════════════════════════════════════════════════════════════════

def download_recon3d_xml(output_dir: str) -> str:
    """
    Download Recon3D SBML/XML from BiGG for FBA experiments.
    This is separate from the .mat file — used only by run_fba_expansion.py.
    """
    import requests
    from tqdm import tqdm
    import gzip

    logger.info("\n" + "=" * 60)
    logger.info("STEP 5: Downloading Recon3D.xml for FBA (optional)")
    logger.info("=" * 60)

    xml_path = os.path.join(output_dir, 'Recon3D.xml')

    if os.path.exists(xml_path):
        size_mb = os.path.getsize(xml_path) / (1024**2)
        if size_mb > 20:  # Recon3D.xml is ~28 MB uncompressed
            logger.info(f"Recon3D.xml already exists ({size_mb:.0f} MB) — skipping")
            return xml_path
        else:
            # File exists but too small — probably truncated or error page
            logger.warning(
                f"Recon3D.xml exists but only {size_mb:.1f} MB "
                f"(expected ~28 MB). Re-downloading..."
            )
            os.remove(xml_path)

    gz_path = xml_path + '.gz'
    url = "http://bigg.ucsd.edu/static/models/Recon3D.xml.gz"

    logger.info(f"Downloading: {url}")
    try:
        resp = requests.get(url, stream=True, timeout=60, allow_redirects=True)
        resp.raise_for_status()

        # Check if response is gzipped content served directly
        content_encoding = resp.headers.get('Content-Encoding', '')
        content_type = resp.headers.get('Content-Type', '')
        total = int(resp.headers.get('content-length', 0))

        logger.info(f"  Content-Type: {content_type}")
        logger.info(f"  Content-Encoding: {content_encoding}")
        logger.info(f"  Content-Length: {total / (1024**2):.1f} MB")

        # Save the raw response first
        with open(gz_path, 'wb') as f:
            with tqdm(total=total, unit='B', unit_scale=True,
                      desc="Recon3D.xml.gz") as pbar:
                for chunk in resp.iter_content(chunk_size=65536):
                    f.write(chunk)
                    pbar.update(len(chunk))

        gz_size = os.path.getsize(gz_path) / (1024**2)
        logger.info(f"  Downloaded: {gz_size:.1f} MB")

        # Try to decompress
        logger.info("Decompressing Recon3D.xml.gz...")
        try:
            with gzip.open(gz_path, 'rb') as f_in:
                with open(xml_path, 'wb') as f_out:
                    shutil.copyfileobj(f_in, f_out)

            xml_size = os.path.getsize(xml_path) / (1024**2)
            if xml_size > gz_size:
                # Successfully decompressed
                os.remove(gz_path)
                logger.info(f"Recon3D.xml ready: {xml_size:.0f} MB → {xml_path}")
            else:
                # Decompression didn't increase size — file wasn't actually gzipped
                # The server may have already decompressed it (Content-Encoding: gzip)
                os.remove(xml_path)
                os.rename(gz_path, xml_path)
                logger.info(f"Recon3D.xml ready (server pre-decompressed): {gz_size:.0f} MB")
        except gzip.BadGzipFile:
            # Not actually gzipped — the server already decompressed
            os.rename(gz_path, xml_path)
            logger.info(f"Recon3D.xml ready (not gzipped): {gz_size:.0f} MB")

        final_size = os.path.getsize(xml_path) / (1024**2)
        if final_size < 10:
            logger.warning(
                f"Recon3D.xml is only {final_size:.1f} MB — expected ~28 MB.\n"
                "The file may be truncated or the server returned an error page.\n"
                "Try downloading manually:\n"
                "  1. Open in browser: http://bigg.ucsd.edu/static/models/Recon3D.xml.gz\n"
                "  2. Decompress the .gz file\n"
                f"  3. Save to: {xml_path}"
            )

    except Exception as e:
        logger.error(f"Failed to download Recon3D.xml: {e}")
        logger.info(
            "Manual download:\n"
            "  1. Open: http://bigg.ucsd.edu/static/models/Recon3D.xml.gz\n"
            f"  2. Decompress and save to: {xml_path}\n"
        )
    return xml_path


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description='Download all raw data for MetaGNN-CRC 690-patient dataset',
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        '--output_dir', default='./raw_downloads',
        help='Directory to save all downloaded files (default: ./raw_downloads)'
    )
    parser.add_argument(
        '--skip_gdc', action='store_true',
        help='Skip GDC RNA-seq download (if already downloaded)'
    )
    parser.add_argument(
        '--skip_cptac', action='store_true',
        help='Skip CPTAC proteomics download'
    )
    parser.add_argument(
        '--skip_fba', action='store_true',
        help='Skip Recon3D.xml download (only needed for FBA experiments)'
    )
    args = parser.parse_args()

    output_dir = os.path.abspath(args.output_dir)
    os.makedirs(output_dir, exist_ok=True)

    logger.info("╔══════════════════════════════════════════════════════════╗")
    logger.info("║  MetaGNN-CRC: Raw Data Download Script                  ║")
    logger.info("╠══════════════════════════════════════════════════════════╣")
    logger.info(f"║  Output directory: {output_dir:<38}║")
    logger.info("╚══════════════════════════════════════════════════════════╝")
    logger.info("")

    check_dependencies()

    results = {}

    # Step 1: GDC RNA-seq
    if not args.skip_gdc:
        results['gdc_manifest'] = download_gdc_rnaseq(output_dir)
    else:
        logger.info("\nSkipping GDC download (--skip_gdc)")
        results['gdc_manifest'] = os.path.join(output_dir, 'gdc_manifest.tsv')

    # Step 2: CPTAC proteomics
    if not args.skip_cptac:
        prot_path, clin_path = download_cptac_proteomics(output_dir)
        results['cptac_tsv'] = prot_path
        results['cptac_clinical'] = clin_path
    else:
        logger.info("\nSkipping CPTAC download (--skip_cptac)")

    # Step 3: Recon3D .mat
    results['recon3d_mat'] = download_recon3d(output_dir)

    # Step 4: HMA tissue-specific GEMs (Zenodo #3583004)
    results['hma_mat'] = download_hma_tissue_gems(output_dir)

    # Step 5: Recon3D.xml (for FBA only)
    if not args.skip_fba:
        results['recon3d_xml'] = download_recon3d_xml(output_dir)
    else:
        logger.info("\nSkipping Recon3D.xml (--skip_fba)")

    # ─── Summary ──────────────────────────────────────────────────────────
    logger.info("\n" + "=" * 60)
    logger.info("DOWNLOAD SUMMARY")
    logger.info("=" * 60)

    all_ok = True
    checks = [
        ("GDC manifest", results.get('gdc_manifest')),
        ("Recon3D .mat", results.get('recon3d_mat')),
        ("HMA tissue GEMs", results.get('hma_mat')),
    ]
    if not args.skip_cptac:
        checks.append(("CPTAC proteomics", results.get('cptac_tsv')))
    if not args.skip_fba:
        checks.append(("Recon3D .xml", results.get('recon3d_xml')))

    for name, path in checks:
        if path and os.path.exists(path):
            size = os.path.getsize(path)
            if size > 0:
                logger.info(f"  ✓ {name}: {path} ({size / (1024**2):.1f} MB)")
            else:
                logger.warning(f"  ✗ {name}: exists but empty!")
                all_ok = False
        else:
            logger.warning(f"  ✗ {name}: NOT FOUND")
            all_ok = False

    # Check GDC download directory
    gdc_dir = os.path.join(output_dir, 'gdc_star_counts')
    if os.path.isdir(gdc_dir):
        n_files = len([d for d in os.listdir(gdc_dir)
                       if os.path.isdir(os.path.join(gdc_dir, d))])
        logger.info(f"  ✓ GDC STAR count files: {n_files} downloaded")
        if n_files < 600:
            logger.warning(f"    Expected ~707 files, only {n_files} found")
            all_ok = False

    logger.info("")
    if all_ok:
        logger.info("All downloads complete! Next step:")
        logger.info("")
        logger.info("  python 00_download_and_generate_690.py \\")
        logger.info(f"      --gdc_dir {gdc_dir} \\")
        logger.info(f"      --gdc_manifest {results.get('gdc_manifest', '')} \\")
        if results.get('cptac_tsv'):
            logger.info(f"      --cptac_tsv {results['cptac_tsv']} \\")
            logger.info(f"      --cptac_clinical {results['cptac_clinical']} \\")
        logger.info(f"      --recon3d_mat {results.get('recon3d_mat', '')} \\")
        logger.info(f"      --hma_mat {results.get('hma_mat', '')} \\")
        logger.info(f"      --output_dir ./processed_690")
    else:
        logger.warning("Some downloads failed — check the log above and retry")
        logger.info("You can re-run this script; it will skip already-downloaded files.")

    # Save download state for resume capability
    state_path = os.path.join(output_dir, 'download_state.json')
    with open(state_path, 'w') as f:
        json.dump({
            'results': {k: v for k, v in results.items() if v is not None},
            'output_dir': output_dir,
            'complete': all_ok,
        }, f, indent=2)


if __name__ == '__main__':
    main()
