#!/usr/bin/env python3
"""Build the standalone supplementary-material document for a paper.

Journals take the supplement as its own file, so the repository produces one alongside the combined
manuscript. Two things have to survive the split. Cross-references from the supplement into the main
text ("Section 4.5") are resolved with the xr package, which reads the main document's .aux, so the
numbers agree with the article a reviewer holds. Citations do not cross that way, and the manuscript
bibliography is a hand-written thebibliography whose every entry prints whether or not it is cited,
so this script extracts only the entries the supplement actually cites and writes a short list of
its own, in the order the supplement first cites them.

Usage: python3 tools/make_supp.py paper1
Writes <paper>/manuscript/<paper>_supp.tex and <paper>/manuscript/body_supp_bib.tex.
Build with: pdflatex <paper>.tex (twice), then pdflatex <paper>_supp.tex (twice).
"""
import os, re, sys

P = sys.argv[1] if len(sys.argv) > 1 else "paper1"
D = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), P, "manuscript")

def read_with_inputs(path, depth=0):
    """The supplement may \\input further bodies (the material relocated when the article was cut to
    length); their citations belong in the supplement's own bibliography too."""
    txt = open(path).read()
    if depth > 3:
        return txt
    def sub(m):
        q = os.path.join(os.path.dirname(path), m.group(1) + ".tex")
        return read_with_inputs(q, depth + 1) if os.path.exists(q) else m.group(0)
    return re.sub(r"\\input\{([^}]*)\}", sub, txt)

supp = read_with_inputs(os.path.join(D, "body_supp.tex"))
bib = open(os.path.join(D, "body_bib.tex")).read()

# the keys the supplement cites, in order of first appearance
keys, seen = [], set()
for m in re.finditer(r"\\cite\{([^}]*)\}", supp):
    for k in (x.strip() for x in m.group(1).split(",")):
        if k and k not in seen:
            seen.add(k); keys.append(k)

# the matching \bibitem blocks, taken verbatim from the manuscript bibliography
blocks = {}
for m in re.finditer(r"\\bibitem\{([^}]*)\}(.*?)(?=\\bibitem\{|\\end\{thebibliography\})", bib, re.S):
    blocks[m.group(1)] = m.group(0).rstrip() + "\n"
missing = [k for k in keys if k not in blocks]
if missing:
    sys.exit(f"{P}: supplement cites entries absent from body_bib.tex: {missing}")

with open(os.path.join(D, "body_supp_bib.tex"), "w") as f:
    f.write("% generated by tools/make_supp.py -- do not edit\n")
    f.write("% only the entries the supplement itself cites; numbering is the supplement's own\n")
    f.write("\\begin{thebibliography}{99}\\small\\itemsep2pt\n\n")
    for k in keys:
        f.write(blocks[k] + "\n")
    f.write("\\end{thebibliography}\n")

# the standalone wrapper: the manuscript preamble, the main document's labels through xr, and the
# same body_supp.tex the combined manuscript uses, so the two can never drift apart
main = open(os.path.join(D, P + ".tex")).read()
pre = main.split("\\title{")[0]
pre = pre.replace("\\input{numbers}", "\\usepackage{xr}\n\\externaldocument{" + P + "}\n\\input{numbers}")
title = re.search(r"\\title\{\\bfseries ([^}]*)\}", main).group(1)
authors = "\n".join(l for l in main.splitlines() if l.startswith(("\\author", "\\affil")))

with open(os.path.join(D, P + "_supp.tex"), "w") as f:
    f.write("% generated by tools/make_supp.py -- do not edit; the content is body_supp.tex,\n")
    f.write("% shared verbatim with the combined manuscript\n")
    f.write(pre)
    f.write("\\title{\\bfseries Supplementary material for\\\\ " + title + "}\n")
    f.write(authors + "\n\\date{}\n\\begin{document}\\maketitle\n")
    f.write("\\noindent Section, table and figure numbers of the form S1 are this document's; numbers\n"
            "without an S refer to the main article, whose numbering this document reproduces.\n")
    # body_supp.tex opens by resetting the counters and printing its own heading, which the standalone
    # document does not need a second time
    f.write("\\renewcommand{\\thesection}{S\\arabic{section}}\n"
            "\\renewcommand{\\thetable}{S\\arabic{table}}\n"
            "\\renewcommand{\\thefigure}{S\\arabic{figure}}\n")
    if P == "paper2":
        f.write("\\renewcommand{\\thesubsection}{S\\arabic{section}.\\arabic{subsection}}\n")
    # the reference list follows the last section on the same page rather than opening a new one,
    # so a short final page of prose is not left nearly empty
    f.write("\\input{body_supp}\n\\vspace{1em}\n\\input{body_supp_bib}\n\\end{document}\n")
# the article alone, which is what a journal takes as the manuscript file: the same bodies as the
# combined document without the supplement, with the supplement's labels supplied through xr so a
# pointer to "Supplementary Section S16" still prints its number.
main_only = main.replace("\\input{numbers}", "\\usepackage{xr}\n\\externaldocument{" + P + "_supp}\n\\input{numbers}")
main_only = main_only.replace("\\clearpage\n\\input{body_supp}\n", "")
assert "\\input{body_supp}" not in main_only, "the supplement is still in the article-only file"
with open(os.path.join(D, P + "_main.tex"), "w") as f:
    f.write("% generated by tools/make_supp.py -- do not edit; the same bodies as " + P + ".tex\n"
            "% without the supplement, for journals that take the manuscript and the supplement apart\n")
    f.write(main_only)

print(f"{P}: wrote {P}_supp.tex, {P}_main.tex and body_supp_bib.tex with {len(keys)} cited entries: {', '.join(keys)}")
